#spring:
#  profiles:
#    active: payment8001
#
#---
## 8001和8002测试用eureka作为注册中心
#server:
#  port: 8001
#
#spring:
#  application:
#    name: cloud-provider-payment
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    url: jdbc:mysql://172.18.8.117:3306/new_assets_db?useAffectedRows=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 7cz.jXR3mycw
#  profiles: payment8001
#
#eureka:
#  client:
#    #表示是否将自己注册进Eurekaserver默认为true。
#    register-with-eureka: true
#    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetchRegistry: true
#    # Eureka Server每8秒拉取服务地址清单后缓存到本地
#    registry-fetch-interval-seconds: 8
#    service-url:
#      defaultZone: http://localhost:7001/eureka
##      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
#  instance:
#    instance-id: payment8001 #添加此处
#    prefer-ip-address: true #添加此处
#    #心跳检测与续约时间
#    #开发时没置小些，保证服务关闭后注册中心能即使剔除服务
#    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
#    lease-renewal-interval-in-seconds: 1
#    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2
#
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.chenyc.springcloud.entities    # 所有Entity别名类所在包
#
##开启
#feign:
#  hystrix:
#    enabled: true
#---
#server:
#  port: 8002
#
#spring:
#  application:
#    name: cloud-provider-payment
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    url: jdbc:mysql://172.18.8.117:3306/new_assets_db?useAffectedRows=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 7cz.jXR3mycw
#  profiles: payment8002
#
#eureka:
#  client:
#    #表示是否将自己注册进Eurekaserver默认为true。
#    register-with-eureka: true
#    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetchRegistry: true
#    # Eureka Server每8秒拉取服务地址清单后缓存到本地
#    registry-fetch-interval-seconds: 8
#    service-url:
#      defaultZone: http://localhost:7001/eureka
##      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
#  instance:
#    instance-id: payment8002 #添加此处
#    prefer-ip-address: true #添加此处
#    #心跳检测与续约时间
#    #开发时没置小些，保证服务关闭后注册中心能即使剔除服务
#    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
#    lease-renewal-interval-in-seconds: 1
#    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2
#
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.chenyc.springcloud.entities    # 所有Entity别名类所在包
#
##开启
#feign:
#  hystrix:
#    enabled: true
#---
## 8003测试用zookeeper作为注册中心
#server:
#  port: 8003
#
#spring:
#  profiles: payment8003
#  application:
#    name: cloud-provider-payment
#  cloud:
#    zookeeper:
#      connect-string: 172.18.8.112:2181
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    url: jdbc:mysql://172.18.8.117:3306/new_assets_db?useAffectedRows=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 7cz.jXR3mycw
#
#
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.chenyc.springcloud.entities    # 所有Entity别名类所在包
#
#---
## 8004测试用consul作为注册中心
#server:
#  port: 8004
#
#spring:
#  profiles: payment8004
#  application:
#    name: cloud-provider-payment
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    url: jdbc:mysql://172.18.8.117:3306/new_assets_db?useAffectedRows=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 7cz.jXR3mycw
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        service-name: ${spring.application.name}
#
#
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.chenyc.springcloud.entities    # 所有Entity别名类所在包